# BINARISATION

In [ ]:
import numpy as np
from sklearn import preprocessing

In [ ]:
x=np.array([[1.2,-2.3,3.7],[2.7,-9.7,-8.6]])
print(x)

[[ 1.2 -2.3  3.7]
 [ 2.7 -9.7 -8.6]]


In [ ]:
x_binarized=preprocessing.Binarizer(threshold=2.1).transform(x)
x_binarized

array([[0., 0., 1.],
       [1., 0., 0.]])

# SCALING -MINMAXSCALER

In [ ]:
x_minmax=preprocessing.MinMaxScaler(feature_range=(0,1))

In [ ]:
x_minmax.fit_transform(x)

array([[0., 1., 1.],
       [1., 0., 0.]])